name: poc
region: nyc
static_sites:
  - name: poc
    github:
      repo: PlayerIUnknown/PoC
      branch: main
      deploy_on_push: true
    source_dir: /
    index_document: index.html
    catchall_document: index.html
